"""empty message

Revision ID: 0b2ecaa49c15
Revises: eb9c763188e1
Create Date: 2018-08-20 11:43:53.302970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2ecaa49c15'
down_revision = 'eb9c763188e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'location')
    # ### end Alembic commands ###
