"""empty message

Revision ID: 5742fcd37906
Revises: b8a6b0855954
Create Date: 2018-08-08 11:10:13.845235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5742fcd37906'
down_revision = 'b8a6b0855954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('group_size', sa.Integer(), nullable=True))
    op.alter_column('guests', 'host_slackid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'host_slackid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('guests', 'group_size')
    # ### end Alembic commands ###
