"""empty message

Revision ID: eb9c763188e1
Revises: 5742fcd37906
Create Date: 2018-08-08 11:29:11.243245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9c763188e1'
down_revision = '5742fcd37906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('submit_tag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'submit_tag')
    # ### end Alembic commands ###
